SRCS = carray.c paxos_malloc.c tcp_receiver.c udp_receiver.c tcp_sendbuf.c udp_sendbuf.c learner.c acceptor_stable_storage.c acceptor.c proposer.c proposer_values_handler.c submit_handle.c config_reader.c

include ../Makefile.conf
include ../Makefile.inc