SRCS = carray.c tcp_receiver.c tcp_sendbuf.c learner.c learner_state.c storage.c acceptor.c acceptor_state.c proposer.c proposer_state.c config_reader.c

include ../Makefile.conf
include ../Makefile.inc
