SRCS = paxos_malloc.c udp_receiver.c udp_sendbuf.c learner.c acceptor_stable_storage.c acceptor.c proposer.c proposer_values_handler.c submit_handle.c

include ../Makefile.conf
include ../Makefile.inc